---
title: "Solution Proposal for BNP Paribas Cardif Claims Management"
author: "Monisha Gopal"
output: md_document
---


## Problem

BNP Paribas Cardif is a global personal insurance provider. They want to automate the process of determining whether a claim can automatically be accepted or needs to be checked further. The problem is then to take the features available to BNP Paribas Cardif and output the probability that a claim can be accepted. 


## Data

This problem comes with a training data set and a test data set (https://www.kaggle.com/c/bnp-paribas-cardif-claims-management/data). The training data set contains 133 variables, 21 of which are categorical variables and 112 of which are numerical variables. 2 of the categorical variables include the ID and the target (whether or not the claim is acceptable). 

``` {r train}
load(file="train.RData")
str(train, list.len=10)
```

## Solution Outline
1. Data preprocessing
    
    a. Go through each feature from v1 to v131,
    
        i. If more than 25% of the values in the feature are missing, remove the feature
    
    b. Treat outliers and missing values
    
        i. Check whether non-missing values are too constant, if so, remove the feature
        ii. For numerical features, replace outliers and missing values with the average of the remaining values
        iii. For categorical features, there are two options,
        
            A. If between 10-25% of the values are missing, create an entirely new categorical feature called "Missing"
            B. Or replace the missing values with the most frequently occurring features
    
    c. Check correlation between features
    
        i. If two features are highly correlated to each other, then remove one of them

2. Feature enrichment (possible methods)
       
    a. Weight of evidence
    b. Informational value

3. Data split 

4. Model
    
    a. Logistic Regression

5. Cross-validation
    
    a. K-fold cross validation

## Deliverables
1. Slide deck explaining process
2. Code
